package com.howManyOfficeDays.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.howManyOfficeDays.greendao.TrackingModel;

import com.howManyOfficeDays.greendao.TrackingModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig trackingModelDaoConfig;

    private final TrackingModelDao trackingModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        trackingModelDaoConfig = daoConfigMap.get(TrackingModelDao.class).clone();
        trackingModelDaoConfig.initIdentityScope(type);

        trackingModelDao = new TrackingModelDao(trackingModelDaoConfig, this);

        registerDao(TrackingModel.class, trackingModelDao);
    }
    
    public void clear() {
        trackingModelDaoConfig.clearIdentityScope();
    }

    public TrackingModelDao getTrackingModelDao() {
        return trackingModelDao;
    }

}
